nodejs:
  applicationPort: 3355
  image: 'hmctsprod.azurecr.io/fact/admin-frontend:latest'
  ingressHost: fact-admin-frontend.{{ .Values.global.environment }}.platform.hmcts.net
  aadIdentityName: fact
  keyVaults:
    fact-kv:
      secrets:
        - AppInsightsInstrumentationKey
  environment:
